# Generated by Django 5.2.16 on 2026-07-30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0005_care_device'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_usercontactprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ease', 'Lakše korišćenje'), ('notification', 'Obaveštenja'), ('sos', 'SOS i bezbednost'), ('issue', 'Problem u radu'), ('idea', 'Predlog')], max_length=16)),
                ('rating', models.CharField(choices=[('good', 'Dobro radi'), ('ok', 'Može bolje'), ('bad', 'Ne radi kako treba')], max_length=8)),
                ('message', models.CharField(max_length=800)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilot_feedback', to='families.family')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-created_at']},
        ),
    ]
