# Generated by Django 5.2.16 on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(model_name='reminder', name='dosage', field=models.CharField(blank=True, max_length=120)),
        migrations.AddField(model_name='reminder', name='instructions', field=models.CharField(blank=True, max_length=300)),
        migrations.AddField(model_name='reminder', name='package_photo', field=models.ImageField(blank=True, upload_to='medicine_packages/')),
    ]
