"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('BRIGA_SECRET_KEY', 'django-insecure-local-development-only')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('BRIGA_DEBUG', '1') == '1'

ALLOWED_HOSTS = os.environ.get('BRIGA_ALLOWED_HOSTS', '127.0.0.1,localhost,testserver').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users', 'families', 'checkins', 'reminders', 'caretasks', 'messaging', 'emergencies', 'alerts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
if os.environ.get('DATABASE_URL'):
    DATABASES['default'] = dj_database_url.config(conn_max_age=600, ssl_require=not DEBUG)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'sr-latn'

TIME_ZONE = 'Europe/Belgrade'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
}
# Produkcioni prilozi (nalazi, fotografije i glasovne poruke) ne smeju ostati na
# privremenom Render fajl-sistemu. R2, S3 ili drugi S3-kompatibilan privatni bucket
# se uključuje ovim promenljivama; lokalni razvoj ostaje bez dodatnog podešavanja.
BRIGA_STORAGE_BUCKET = os.environ.get('BRIGA_STORAGE_BUCKET', '')
BRIGA_DURABLE_MEDIA_CONFIGURED = bool(BRIGA_STORAGE_BUCKET)
if BRIGA_DURABLE_MEDIA_CONFIGURED:
    AWS_ACCESS_KEY_ID = os.environ.get('BRIGA_STORAGE_ACCESS_KEY_ID', '')
    AWS_SECRET_ACCESS_KEY = os.environ.get('BRIGA_STORAGE_SECRET_ACCESS_KEY', '')
    AWS_STORAGE_BUCKET_NAME = BRIGA_STORAGE_BUCKET
    AWS_S3_ENDPOINT_URL = os.environ.get('BRIGA_STORAGE_ENDPOINT_URL', '') or None
    AWS_S3_REGION_NAME = os.environ.get('BRIGA_STORAGE_REGION', 'auto')
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = True
    AWS_QUERYSTRING_EXPIRE = 300
    STORAGES['default'] = {'BACKEND': 'storages.backends.s3.S3Storage'}
VAPID_PUBLIC_KEY = os.environ.get('BRIGA_VAPID_PUBLIC_KEY', '')
VAPID_PRIVATE_KEY = os.environ.get('BRIGA_VAPID_PRIVATE_KEY', '')
VAPID_SUBJECT = os.environ.get('BRIGA_VAPID_SUBJECT', 'mailto:podrska@briga-plus.rs')
LOGIN_REDIRECT_URL = 'pocetna'
LOGIN_URL = 'prijava'
LOGOUT_REDIRECT_URL = 'prijava'
CSRF_TRUSTED_ORIGINS = [host for host in os.environ.get('BRIGA_CSRF_TRUSTED_ORIGINS', '').split(',') if host]
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
