# Generated by Django 5.2.16 on 2026-07-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('relationship', models.CharField(blank=True, max_length=80)),
                ('phone', models.CharField(max_length=32)),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='families.family')),
            ],
            options={'ordering': ['priority', 'name']},
        ),
    ]
